spring:
  application:
    name:userservice
  datasource:
      url: jdbc:postgresql://localhost:5432/fitness-app
      username: postgres
      password: Stark@321
  jpa:
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.PostgreSQLDialect


